--- 
abstract: Sensible default end action.
author: Marcus Ramberg <marcus@thefeed.no>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Action-RenderView
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 5.70
  Test::More: 0
version: 0.05
